///$tab Main

$(Include=..\..\..\general_functions\configIni.txt);
$(Include=..\..\config\projectConfig.txt);

Call dataSourcePaths;
Call englishUSVars;
Call connectToCarSalesDB;

sales:
SQL SELECT *
FROM "sales_cars".dbo.sales;

sales_items:
SQL SELECT *
FROM "sales_cars".dbo."sales_item";

Call createFolders('$(vPathMirrors)','$(vProjectName)');
Call storeFiles('$(vPathMirrors)','$(vProjectName)',Null(),Null());